import { CertificateInfo } from './certificate'
import { CostInfo } from './cost'
import { ApproveInfo } from './approve'
import { RoleInfo } from './role'
import { PolicyInfo } from './policy'
import { DepartmentInfo } from './department'
import { EmployeeInfo } from './employee'
import { CabinInfo } from './cabin'
import { ReasonInfo } from './reason'
import { PassengerInfo } from './passenger'
import { ProductInfo } from './product'
import { AccountInfo } from './account'
import { PaymentInfo } from './payment'
import { OrderInfo } from './order'
import { PermissionInfo } from './permission'
import { BusinessTrip } from './businessTrip'
import { NationalityInfo } from './nationality'
import { IM } from './im'
import { Log } from './log'
import { Knowledge } from './knowledge'
import { DestInfo } from './dest'

export { DestInfo, Knowledge, Log, IM, NationalityInfo, BusinessTrip, OrderInfo, PaymentInfo, AccountInfo, ProductInfo, CertificateInfo, CostInfo, ApproveInfo, RoleInfo, PolicyInfo, DepartmentInfo, EmployeeInfo, CabinInfo, ReasonInfo, PassengerInfo, PermissionInfo }